### ISSUE TITLE
Sidebar text overlaps if window is not wide enough

### ISSUE THREAD

**Issue by exp111** [zhol0777/is-this-good#5]
Sidebar text goes into main content if width is smaller than 1500px, but larger than 1063px

Should be around 1200px?
![grafik](https://user-images.githubusercontent.com/17885980/167302243-a5bae6ba-2f5b-4757-aa52-9a7ece900125.png)

1064px:
![grafik](https://user-images.githubusercontent.com/17885980/167302318-0a5a7469-7fa3-4cbe-96b8-49926bfb5e3f.png)

1063px:
![grafik](https://user-images.githubusercontent.com/17885980/167302334-d7e880a0-3a79-481f-afd3-05e044619dcf.png)

**Comment by zhol0777** [comment]
https://github.com/zhol0777/is-this-good/blob/gh-pages/_sass/color_schemes/dark-mod.scss#L21-L22
i am not very good with sass
lemme try to come up with something better

**Comment by zhol0777** [comment]
https://github.com/zhol0777/is-this-good/commit/fd4bcb4c807f1c5f8338ae97e57fba48ac67b698 alright it should suck less

**Comment by exp111** [comment]
Yea it looks good now.

Another thing:
![grafik](https://user-images.githubusercontent.com/17885980/167566249-2e7e5876-aef6-41af-bfdc-24f93c7ad8f5.png)
The text is only black on firefox, not on edge
The css seems to come from 
![grafik](https://user-images.githubusercontent.com/17885980/167567466-9efc7074-30cb-4a36-954f-41b9f0ae180e.png)

Apparently this isn't your fault but the theme's one (as it happens in the dark "just the docs" theme too) or its on firefox
