### ISSUE TITLE
Thockpop (vendor) is now in Houston Texas

### ISSUE THREAD

**Issue by Celesian** [zhol0777/is-this-good#8]
![image](https://user-images.githubusercontent.com/49375840/176245483-1b6baff9-1ecc-44ec-a0de-8454779d0cc6.png)

Link from the thockpop discord directly https://discord.com/channels/864946561435566080/864951041283194900/985984600532721694

**Comment by zhol0777** [comment]
🙏 
fixed in  https://github.com/zhol0777/is-this-good/commit/ee01b3f7951237b4f7293c99b7c4e4bdd2d1a043
